#!/bin/bash

# =============================================================================
# MCP Server HTTPS Setup Script
# =============================================================================
# This script installs Caddy and configures HTTPS reverse proxy for MCP servers
#
# Prerequisites:
#   1. DNS: Point mcp.ctxprotocol.com to your VPS IP
#   2. MCP servers running on ports 4001-4004
#
# Usage:
#   chmod +x setup-caddy-https.sh
#   sudo ./setup-caddy-https.sh
# =============================================================================

set -e  # Exit on error

# =============================================================================
# CONFIGURATION - Edit these values for your setup
# =============================================================================

DOMAIN="mcp.ctxprotocol.com"

# MCP Server ports (local)
BLOCKNATIVE_PORT=4001
HYPERLIQUID_PORT=4002
POLYMARKET_PORT=4003
EXA_PORT=4004

# Set to "yes" to close raw ports after setup (recommended for production)
CLOSE_RAW_PORTS="no"

# =============================================================================
# COLORS FOR OUTPUT
# =============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# =============================================================================
# PRE-FLIGHT CHECKS
# =============================================================================

echo ""
echo "=============================================="
echo "  MCP Server HTTPS Setup"
echo "=============================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root (use sudo)"
    exit 1
fi

# Check if domain is configured
log_info "Checking DNS for ${DOMAIN}..."
if ! host "${DOMAIN}" > /dev/null 2>&1; then
    log_warn "DNS for ${DOMAIN} may not be configured yet."
    log_warn "Make sure to add an A record pointing to this server's IP."
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    RESOLVED_IP=$(dig +short "${DOMAIN}" | head -n1)
    log_info "DNS resolves to: ${RESOLVED_IP}"
fi

# =============================================================================
# INSTALL CADDY
# =============================================================================

log_info "Installing Caddy..."

# Check if Caddy is already installed
if command -v caddy &> /dev/null; then
    log_info "Caddy is already installed: $(caddy version)"
else
    # Install Caddy (Debian/Ubuntu)
    apt-get update -qq
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https curl

    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg 2>/dev/null
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null

    apt-get update -qq
    apt-get install -y -qq caddy

    log_info "Caddy installed: $(caddy version)"
fi

# =============================================================================
# CREATE CADDYFILE
# =============================================================================

log_info "Creating Caddyfile..."

# Backup existing Caddyfile if it exists
if [ -f /etc/caddy/Caddyfile ]; then
    cp /etc/caddy/Caddyfile /etc/caddy/Caddyfile.backup.$(date +%Y%m%d%H%M%S)
    log_info "Backed up existing Caddyfile"
fi

cat > /etc/caddy/Caddyfile << EOF
# =============================================================================
# MCP Server Reverse Proxy Configuration
# Generated by setup-caddy-https.sh
# =============================================================================

${DOMAIN} {
    # Logging
    log {
        output file /var/log/caddy/mcp-access.log
        format json
    }

    # Health check endpoint
    handle /health {
        respond "OK" 200
    }

    # Blocknative (SSE transport)
    handle /blocknative/* {
        uri strip_prefix /blocknative
        reverse_proxy localhost:${BLOCKNATIVE_PORT}
    }

    # Hyperliquid (HTTP Streaming transport)
    handle /hyperliquid/* {
        uri strip_prefix /hyperliquid
        reverse_proxy localhost:${HYPERLIQUID_PORT}
    }

    # Polymarket (HTTP Streaming transport)
    handle /polymarket/* {
        uri strip_prefix /polymarket
        reverse_proxy localhost:${POLYMARKET_PORT}
    }

    # Exa (HTTP Streaming transport)
    handle /exa/* {
        uri strip_prefix /exa
        reverse_proxy localhost:${EXA_PORT}
    }

    # Fallback - return 404 for unknown paths
    handle {
        respond "Not Found" 404
    }
}
EOF

log_info "Caddyfile created at /etc/caddy/Caddyfile"

# Create log directory
mkdir -p /var/log/caddy
chown caddy:caddy /var/log/caddy

# =============================================================================
# VALIDATE AND START CADDY
# =============================================================================

log_info "Validating Caddy configuration..."
caddy validate --config /etc/caddy/Caddyfile

log_info "Starting Caddy service..."
systemctl daemon-reload
systemctl enable caddy
systemctl restart caddy

# Wait for Caddy to start
sleep 3

# Check if Caddy is running
if systemctl is-active --quiet caddy; then
    log_info "Caddy is running!"
else
    log_error "Caddy failed to start. Check logs with: journalctl -u caddy -f"
    exit 1
fi

# =============================================================================
# CONFIGURE FIREWALL (OPTIONAL)
# =============================================================================

if [ "${CLOSE_RAW_PORTS}" = "yes" ]; then
    log_info "Configuring firewall to close raw MCP ports..."
    
    # Install ufw if not present
    if ! command -v ufw &> /dev/null; then
        apt-get install -y -qq ufw
    fi

    # Allow SSH (important - don't lock yourself out!)
    ufw allow 22/tcp

    # Allow HTTP/HTTPS for Caddy
    ufw allow 80/tcp
    ufw allow 443/tcp

    # Deny direct access to MCP ports from outside
    ufw deny ${BLOCKNATIVE_PORT}/tcp
    ufw deny ${HYPERLIQUID_PORT}/tcp
    ufw deny ${POLYMARKET_PORT}/tcp
    ufw deny ${EXA_PORT}/tcp

    # Enable firewall
    ufw --force enable

    log_info "Firewall configured. Raw ports are now blocked from external access."
else
    log_warn "Raw ports are still open. Set CLOSE_RAW_PORTS=\"yes\" to secure them."
fi

# =============================================================================
# SUMMARY
# =============================================================================

echo ""
echo "=============================================="
echo "  Setup Complete!"
echo "=============================================="
echo ""
echo "Your new HTTPS endpoints:"
echo ""
echo "  Blocknative:  https://${DOMAIN}/blocknative/sse"
echo "  Hyperliquid:  https://${DOMAIN}/hyperliquid/mcp"
echo "  Polymarket:   https://${DOMAIN}/polymarket/mcp"
echo "  Exa:          https://${DOMAIN}/exa/mcp"
echo ""
echo "Health check:   https://${DOMAIN}/health"
echo ""
echo "=============================================="
echo "  Next Steps"
echo "=============================================="
echo ""
echo "1. Test the health endpoint:"
echo "   curl https://${DOMAIN}/health"
echo ""
echo "2. Test an MCP endpoint:"
echo "   curl -X POST https://${DOMAIN}/hyperliquid/mcp \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"jsonrpc\":\"2.0\",\"method\":\"tools/list\",\"id\":1}'"
echo ""
echo "3. Update your database with the new endpoints"
echo ""
echo "4. View Caddy logs:"
echo "   tail -f /var/log/caddy/mcp-access.log"
echo ""

if [ "${CLOSE_RAW_PORTS}" = "no" ]; then
    echo "=============================================="
    echo "  Security Note"
    echo "=============================================="
    echo ""
    echo "Raw ports (4001-4004) are still open!"
    echo "For production, edit this script and set:"
    echo "  CLOSE_RAW_PORTS=\"yes\""
    echo "Then re-run the script."
    echo ""
fi

